### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by cenchaojun** [rajeevyasarla/3SD#6]
thank you for your nice work.👍. i try to run this code, but I don't understand the setting of the data.
What is the difference between data_dir and syn_data_dir
![image](https://user-images.githubusercontent.com/48192514/199883608-fa5321eb-e309-48dd-a3f7-005f58dba953.png)
best wishes to you.❤️

**Comment by rajeevyasarla** [comment]
you can ignore syn_data_dir and comment lines 267 and 268 . it was actually used for input images without edges directory.
